apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-http
  template:
    metadata:
      labels:
        app: simple-http
    spec:
      containers:
        - name: simple-http
          image: strm/helloworld-http
          ports:
            - containerPort: 80
